
//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WWWBewertungPortal.Models.Datenbank
{

using System;
    using System.Collections.Generic;
    
public partial class Tab_Lokation_Photo
{

    public int Id { get; set; }

    public string Uri { get; set; }

    public int Tab_LokationId { get; set; }



    public virtual Tab_Lokation Tab_Lokation { get; set; }

}

}
